apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-telemetry-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      istio: mixer
  endpoints:
  - port: prometheus
    interval: 10s
