apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: istio-system
spec:
  rules:
  - host: kiali.0.0.0.0.nip.io
    http:
      paths:
      - backend:
          serviceName: kiali
          servicePort: 20001
