{
 "title": "Netcore Counter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "interval",
    "label": "Intervalo",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Netcore Counter User",
   "type": "graph",
   "description": "Peticiones al servicio",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_request_total{namespace=\"$namespace\", path!~\".*/Health/live\", path!~\".*/Health/ready\", job=~\".*netcore-counter-user.*\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Netcore Counter Next",
   "type": "graph",
   "description": "Peticiones al servicio",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_request_total{namespace=\"$namespace\", path!~\".*/Health/live\", path!~\".*/Health/ready\", job=~\".*netcore-counter-next.*\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Netcore Counter Redis",
   "type": "graph",
   "description": "Peticiones al servicio",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_request_total{namespace=\"$namespace\", path!~\".*/Health/live\", path!~\".*/Health/ready\", job=~\".*netcore-counter-redis.*\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memoria Asignada",
   "type": "graph",
   "description": "Memoria Asignada",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{namespace=\"$namespace\"} /1024/1024) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Número de Threads",
   "type": "graph",
   "description": "Número total de Threads",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_num_threads{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Número de Handles Abiertos",
   "type": "graph",
   "description": "Número de Handles abiertos",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_handles{namespace=\"$namespace\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Working Set del Proceso",
   "type": "graph",
   "description": "Working Set del proceso",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_working_set_bytes{namespace=\"$namespace\"} /1024/1024) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Llamadas al GC",
   "type": "graph",
   "description": "Llamadas al Garbage Collector",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_collection_count_total{namespace=\"$namespace\"}[$interval])) by (job, generation)",
     "legendFormat": "{{job}} Generation-{{generation}}"
    }
   ]
  }
 ]
}